#!/usr/bin/env ruby
require_relative 'lib/direction.rb'
include Direction

command = ARGV[0]
grid_size_array = command.scan(/\d\w\d/).first.split("x")
coordinates = format_coordinates(command)
puts delivery_instructions(coordinates, grid_size_array).join
